trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Instalar Node.js'

  - script: |
      npm install --force
    displayName: 'Instalar dependências'

  # - script: |
  #     npm run build
  #   displayName: 'Executar build'

  - script: npm cache clean --force
    displayName: 'Limpar cache do npm'

  - script: echo "//registry.npmjs.org/:_authToken=$(NPM_TOKEN)" > ~/.npmrc
    displayName: 'Autenticar com o npm'

  - script: |
      npm run build
      npm publish --access public
    displayName: 'Publicar no npm'
#  - task: PublishPipelineArtifact@1
#    inputs:
#      targetPath: 'dist'  # O caminho correto
#      artifact: 'drop'
#      publishLocation: 'pipeline'
#    displayName: 'Publicar artefato da build'
